version: '3'

services:
  db_brisapix_dev:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DEV_POSTGRES_DB}
      POSTGRES_PASSWORD: ${DEV_POSTGRES_PASSWORD}
      POSTGRES_USER: ${DEV_POSTGRES_USER}
      POSTGRES_PORT: ${DEV_POSTGRES_PORT} 
    ports:
      - "${DEV_POSTGRES_PORT}:5432"